# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.SlugField(max_length=32, unique=True)),
                ('regid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=64, null=True)),
                ('kerberos_active_permitted', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'uw_service_endorsement_endorsee',
            },
        ),
        migrations.CreateModel(
            name='EndorsementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_code', models.SmallIntegerField(choices=[(233, b'UW Office 365 Education'), (234, b'UW Office 365 Education Dogfood'), (144, b'Google Apps'), (145, b'Google Apps Test'), (237, b'UW Project Server Online user access'), (238, b'UW Project Server Online user access Dogfood')])),
                ('datetime_endorsed', models.DateTimeField(null=True)),
                ('datetime_renewed', models.DateTimeField(null=True)),
                ('datetime_expired', models.DateTimeField(null=True)),
                ('endorsee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.Endorsee')),
            ],
            options={
                'db_table': 'uw_service_endorsement_endorsement',
            },
        ),
        migrations.CreateModel(
            name='Endorser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.SlugField(max_length=32, unique=True)),
                ('regid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_valid', models.BooleanField(null=True)),
                ('last_visit', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'uw_service_endorsement_endorser',
            },
        ),
        migrations.AddField(
            model_name='endorsementrecord',
            name='endorser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.Endorser'),
        ),
        migrations.AlterUniqueTogether(
            name='endorsementrecord',
            unique_together=set([('endorser', 'subscription_code', 'endorsee')]),
        ),
    ]
