# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndorseeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'uw_service_endorsement_endorsee_email',
            },
        ),
        migrations.AddField(
            model_name='endorsementrecord',
            name='datetime_emailed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='endorsee',
            name='kerberos_active_permitted',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endorser',
            name='is_valid',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='endorseeemail',
            name='endorsee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.Endorsee'),
        ),
    ]
