# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0002_auto_20180227_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrecord',
            name='category_code',
            field=models.SmallIntegerField(choices=[(235, b'UW Office 365 Education'), (234, b'UW Office 365 Education')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endorsementrecord',
            name='subscription_code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='endorsementrecord',
            unique_together=set([('endorser', 'category_code', 'endorsee')]),
        ),
    ]
