# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0004_remove_endorsementrecord_subscription_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrecord',
            name='reason',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
