# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0005_endorsementrecord_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsementrecord',
            name='category_code',
            field=models.SmallIntegerField(choices=[(235, b'UW Office 365 Education'), (234, b'UW Google Suite')]),
        ),
    ]
