# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0006_auto_20180413_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrecord',
            name='accept_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='endorsementrecord',
            name='accept_salt',
            field=models.CharField(default='abcdef01abcdef02abcdef03abcdef04', max_length=32),
            preserve_default=False,
        ),
    ]
