# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0007_auto_20180417_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrecord',
            name='datetime_created',
            field=models.DateTimeField(null=True),
        ),
    ]
