# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0008_endorsementrecord_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorser',
            name='display_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
