# Generated by Django 1.11.10 on 2018-05-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0010_auto_20180507_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorseeemail',
            name='endorser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='endorsement.Endorser'),
        ),
    ]
