# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-20 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0012_endorsee_is_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrecord',
            name='is_deleted',
            field=models.NullBooleanField(),
        ),
    ]
