# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0013_endorsementrecord_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsementrecord',
            name='accept_id',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
