# Generated by Django 1.11.13 on 2018-09-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0014_auto_20180620_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsee',
            name='display_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='endorser',
            name='display_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
