# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-18 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0015_auto_20180906_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorser',
            name='datetime_emailed',
            field=models.DateTimeField(null=True),
        ),
    ]
