# Generated by Django 2.2.5 on 2019-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0016_endorser_datetime_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrecord',
            name='datetime_notice_1_emailed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='endorsementrecord',
            name='datetime_notice_2_emailed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='endorsementrecord',
            name='datetime_notice_3_emailed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='endorsementrecord',
            name='datetime_notice_4_emailed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='endorsementrecord',
            name='category_code',
            field=models.SmallIntegerField(choices=[(235, 'UW Office 365'), (234, 'UW G Suite')]),
        ),
    ]
