# Generated by Django 2.2.24 on 2021-06-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0017_auto_20191004_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsementrecord',
            name='category_code',
            field=models.SmallIntegerField(choices=[(235, 'UW Office 365'), (234, 'UW G Suite'), (236, 'Canvas and Panopto'), (237, 'UW Zoom Licensed'), (238, 'UW Zoom Basic'), (239, 'Husky OnNet Basic')]),
        ),
    ]
