# Generated by Django 3.2.15 on 2022-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0019_auto_20220516_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='right_id',
            field=models.SlugField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='endorsee',
            name='is_person',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsee',
            name='kerberos_active_permitted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
