# Generated by Django 3.2.19 on 2023-06-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0020_auto_20220927_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='is_reconcile',
            field=models.BooleanField(null=True),
        ),
    ]
