# Generated by Django 3.2.19 on 2023-06-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0021_accessrecord_is_reconcile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsementrecord',
            name='category_code',
            field=models.SmallIntegerField(choices=[(235, 'UW Office 365'), (291, 'UW Office 365'), (234, 'UW Google'), (236, 'Canvas and Panopto'), (237, 'UW Zoom Licensed'), (238, 'UW Zoom Basic'), (239, 'Husky OnNet for Affiliates')]),
        ),
    ]
