# Generated by Django 3.2.21 on 2023-09-13 21:33

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    def back_fill_access_right(apps, schema_editor):
        AccessRecord = apps.get_model('endorsement', 'AccessRecord')
        AccessRight = apps.get_model('endorsement', 'AccessRight')
        for record in AccessRecord.objects.all():
            right, created = AccessRight.objects.get_or_create(
                name=record.right_id, display_name=record.right_name)

            record.access_right = right
            record.save()

    dependencies = [
        ('endorsement', '0022_alter_endorsementrecord_category_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=24, null=True)),
                ('display_name', models.SlugField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'uw_service_endorsement_access_right',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('access_right'), models.Model),
        ),
        migrations.CreateModel(
            name='AccessRecordConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_noted', models.DateTimeField(null=True)),
                ('accessee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.accessee')),
                ('accessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.accessor')),
                ('rights', models.ManyToManyField(to='endorsement.AccessRight')),
            ],
            options={
                'db_table': 'uw_service_endorsement_access_record_conflict',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('access_record'), models.Model),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='access_right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='endorsement.accessright'),
        ),
        migrations.RunPython(
            back_fill_access_right,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
