# Generated by Django 3.2.23 on 2024-02-29 02:50

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0024_auto_20230913_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('member'), models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('role'), models.Model),
        ),
        migrations.CreateModel(
            name='SharedDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_id', models.SlugField(max_length=32)),
                ('drive_name', models.CharField(max_length=128)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('shared_drive'), models.Model),
        ),
        migrations.CreateModel(
            name='SharedDriveQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_unit', models.CharField(max_length=32)),
                ('quota_limit', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('shared_drive_tier'), models.Model),
        ),
        migrations.CreateModel(
            name='SharedDriveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.SlugField(max_length=32, null=True)),
                ('state', models.CharField(max_length=128, null=True)),
                ('acted_as', models.SlugField(max_length=32, null=True)),
                ('datetime_created', models.DateTimeField(null=True)),
                ('datetime_emailed', models.DateTimeField(null=True)),
                ('datetime_notice_1_emailed', models.DateTimeField(null=True)),
                ('datetime_notice_2_emailed', models.DateTimeField(null=True)),
                ('datetime_notice_3_emailed', models.DateTimeField(null=True)),
                ('datetime_notice_4_emailed', models.DateTimeField(null=True)),
                ('datetime_granted', models.DateTimeField(null=True)),
                ('datetime_renewed', models.DateTimeField(null=True)),
                ('datetime_expired', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(null=True)),
                ('shared_drive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.shareddrive')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('shared_drive_record'), models.Model),
        ),
        migrations.CreateModel(
            name='SharedDriveMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.member')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.role')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('shared_drive_member'), models.Model),
        ),
        migrations.AddField(
            model_name='shareddrive',
            name='drive_quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.shareddrivequota'),
        ),
        migrations.AddField(
            model_name='shareddrive',
            name='members',
            field=models.ManyToManyField(to='endorsement.SharedDriveMember'),
        ),
    ]
