# Generated by Django 3.2.25 on 2024-04-27 00:58

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0025_auto_20240228_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITBillSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_remote', models.SlugField(max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('url', models.CharField(max_length=256, null=True)),
                ('state', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Provisioning'), (2, 'Deployed'), (3, 'Deprovision'), (4, 'Closed'), (5, 'Cancelled')], default=0)),
                ('query_priority', models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high')], default=1)),
                ('query_datetime', models.DateTimeField(null=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('itbill_subscription'), models.Model),
        ),
        migrations.RenameField(
            model_name='shareddrivequota',
            old_name='org_unit',
            new_name='org_unit_id',
        ),
        migrations.RenameField(
            model_name='shareddrivequota',
            old_name='name',
            new_name='org_unit_name',
        ),
        migrations.RenameField(
            model_name='shareddriverecord',
            old_name='datetime_granted',
            new_name='datetime_accepted',
        ),
        migrations.RemoveField(
            model_name='shareddriverecord',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shareddriverecord',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='shareddrive',
            name='drive_usage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shareddrive',
            name='query_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='SharedDriveAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, 'Accept'), (1, 'Revoke')], default=0)),
                ('datetime_accepted', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.member')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('shared_drive_acceptance'), models.Model),
        ),
        migrations.AddField(
            model_name='shareddriverecord',
            name='acceptance',
            field=models.ManyToManyField(blank=True, to='endorsement.SharedDriveAcceptance'),
        ),
        migrations.AddField(
            model_name='shareddriverecord',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='endorsement.itbillsubscription'),
        ),
    ]
