# Generated by Django 3.2.25 on 2024-05-03 21:36

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import endorsement.util.key_remote


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0026_auto_20240426_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITBillProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField()),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('itbill_provision'), models.Model),
        ),
        migrations.RemoveField(
            model_name='itbillsubscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itbillsubscription',
            name='url',
        ),
        migrations.AlterField(
            model_name='itbillsubscription',
            name='key_remote',
            field=models.SlugField(default=endorsement.util.key_remote.key_remote, max_length=32),
        ),
        migrations.AlterField(
            model_name='itbillsubscription',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'draft'), (1, 'provisioning'), (2, 'deployed'), (3, 'deprovision'), (4, 'closed'), (5, 'cancelled')], default=0),
        ),
        migrations.CreateModel(
            name='ITBillQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('stage', models.CharField(max_length=32, null=True)),
                ('provision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.itbillprovision')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('itbill_quantity'), models.Model),
        ),
        migrations.AddField(
            model_name='itbillprovision',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.itbillsubscription'),
        ),
    ]
