# Generated by Django 3.2.25 on 2024-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0027_auto_20240503_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='netid',
        ),
        migrations.AlterField(
            model_name='shareddrive',
            name='members',
            field=models.ManyToManyField(blank=True, to='endorsement.SharedDriveMember'),
        ),
    ]
