# Generated by Django 3.2.25 on 2024-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0027_auto_20240503_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddrive',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
