# Generated by Django 3.2.25 on 2024-05-08 19:42

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0029_auto_20240508_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDriveAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.SmallIntegerField(choices=[(0, 'Accept'), (1, 'Revoke')], default=0)),
                ('datetime_accepted', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.member')),
                ('shared_drive_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endorsement.shareddriverecord')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('shared_drive_acceptance'), models.Model),
        ),
    ]
