# Generated by Django 3.2.25 on 2024-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0030_shareddriveacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddriverecord',
            name='datetime_over_quota_emailed',
            field=models.DateTimeField(null=True),
        ),
    ]
