# Generated by Django 3.2.25 on 2024-05-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0028_shareddrive_is_deleted'),
        ('endorsement', '0031_shareddriverecord_datetime_over_quota_emailed'),
    ]

    operations = [
    ]
