# Generated by Django 3.2.25 on 2024-05-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0032_merge_20240520_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itbillsubscription',
            name='key_remote',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='shareddrive',
            name='drive_id',
            field=models.SlugField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shareddrivequota',
            name='org_unit_name',
            field=models.CharField(max_length=64),
        ),
    ]
