# Generated by Django 3.2.25 on 2024-05-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0033_auto_20240520_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddrivequota',
            name='quota_limit',
            field=models.IntegerField(default=0),
        ),
    ]
