# Generated by Django 3.2.25 on 2024-05-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0034_alter_shareddrivequota_quota_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareddriveacceptance',
            old_name='datetime_accepted',
            new_name='datetime_created',
        ),
        migrations.RemoveField(
            model_name='shareddriverecord',
            name='acted_as',
        ),
        migrations.RemoveField(
            model_name='shareddriverecord',
            name='datetime_renewed',
        ),
        migrations.AddField(
            model_name='shareddriveacceptance',
            name='acted_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acted_as', to='endorsement.member'),
        ),
        migrations.AlterField(
            model_name='shareddriveacceptance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member', to='endorsement.member'),
        ),
    ]
