# Generated by Django 3.2.25 on 2024-05-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0035_auto_20240522_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddrive',
            name='drive_usage',
            field=models.FloatField(null=True),
        ),
    ]
