# Generated by Django 3.2.25 on 2024-07-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0036_alter_shareddrive_drive_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddrive',
            name='drive_name',
            field=models.TextField(),
        ),
    ]
