# Generated by Django 3.2.25 on 2024-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0037_alter_shareddrive_drive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddriverecord',
            name='datetime_deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
