# Generated by Django 5.2.11 on 2026-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsement', '0038_shareddriverecord_datetime_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='is_manual_sync',
            field=models.BooleanField(null=True),
        ),
    ]
