dist: trusty
sudo: required

env:
  - COVERAGE_FILE=endorsement/.coverage

services:
  - docker

install:
  - docker-compose build

before_script:
  - npm install coveralls
  - docker-compose run --rm --no-deps -u root --entrypoint='bash -c ". bin/activate && bin/python manage.py migrate"' app

script:
  - docker-compose run --rm --no-deps -u root --entrypoint='bash -c "pip install pycodestyle && /usr/local/bin/pycodestyle endorsement/ --exclude=migrations,statics"' app
  - docker-compose run --rm --no-deps -u root --entrypoint='bash -c "apt-get install -y nodejs npm && npm install --save-dev webpack && npm install -g jshint npx webpack-cli && npx webpack --mode=development && jshint endorsement/static/endorsement/js --verbose"' app
  - docker-compose run --rm --no-deps -u root --entrypoint='bash -c ". bin/activate && export COVERAGE_FILE=${COVERAGE_FILE} && pip install coverage && pip install python-coveralls && coverage run --source=endorsement/ --omit=endorsement/migrations/* manage.py test endorsement"' app

after_script:
  - mv ${COVERAGE_FILE} .
  - coveralls
notifications:
