sudo: false
services:
  - docker
install:
  - docker-compose up --build
script:
  - docker exec -u root app bash -c '. docker/test.sh'
after_success:
  - docker cp app:/app/.coverage ./.coverage
  - coveralls
