sudo: false
language: python
services:
  - memcached
python:
  - "2.7"

install:
  - pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - pip install MySQL-python
  - npm install jquery
  - npm install -g jshint
  - npm install -g mocha
  - npm install -g istanbul
  - npm install jsdom
  - npm install sinon
  - npm install coveralls
  - gem install coveralls-lcov
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate

script:
  - pep8 endorsement/ --exclude=migrations,endorsement/static/vendor,endorsement/static/images,endorsement/static/fonts
#  - jshint endorsement/static/js/  --verbose
#  - mocha endorsement/static/js/test/ --recursive
  - coverage run --source=endorsement/ --omit=endorsement/migrations/* manage.py test endorsement
  - coveralls-lcov -v -n coverage/lcov.info > js-coverage.json
after_script:
  - coveralls --merge=js-coverage.json
notifications:
