dist: xenial
sudo: false
language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - gcc-4.8
      - unixodbc-dev
install:
  - sudo apt-get install -qq python-dev libxml2-dev libxmlsec1-dev
  - pip install pycodestyle
before_script:
  - pip install coveralls
  - npm install
  - pip install .
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate
  - npx webpack --verbose --mode=development
script:
  - pycodestyle endorsement/ --exclude=migrations,static
  - jshint endorsement/static/endorsement/js/ --verbose
  - coverage run --source=endorsement/ --omit=endorsement/migrations/* manage.py test endorsement
after_success:
  - coveralls



