sudo: false
services:
- docker
before_install:
- export IMAGE_REPO="acait/prt"
- export IMAGE_TAG="${IMAGE_REPO}:$(git rev-parse --short=7 HEAD)"
install:
- docker build -t "$IMAGE_TAG" .
script:
- docker run -u root -it -v /tmp:/coverage -e "ENV=localdev" -e "AUTH=SAML_MOCK" "$IMAGE_TAG" bash -c ". ./docker/test.sh"
- cp /tmp/.coverage ./.coverage
after_success:
- coveralls
- |
  if [ "$TRAVIS_BRANCH" == "develop" ]; then
    echo "Pushing $IMAGE_TAG";
    docker images "$IMAGE_REPO";
    echo -n "$DOCKER_PASS" | docker login --username="$DOCKER_USER" --password-stdin;
    docker push "$IMAGE_TAG";
  fi
env:
  global:
  - secure: MA1UlezkBQn9/LVoFjG3QeHKYe8e7nH5h6Wv6J/xF6sad+wXfQwybtsflN8l/1dMLB6dbjDPh2OdIXq2i1CrDXl024mdsyyacE7DN9yGnAYIlLjbhY6tR9QnRA3sMloJS13h/WVTiG5AYdY5Y/T0vshDteXpYXEwuDzALNa1YyTgXO/NQYoV8m4fHaJDpZQBCIAtV/YRUzf5i8RQYUxEJX4I7xAoo8n5r7Z6xf9gL++xhGVAMN2eMEZPAsdZUEGk7FuP5kuBX+nW6igBktMqJGUZJyU8ybliIFYnKSLD4vBgOr7eNgsf6ULd5senNjPsnf6ZKXikp934rTSJaZhh3i81EnLhl3+WlYQnfDJv3bjkUkr/PiDRHn+dw5CKJL+eDalTpCtD27cEO6/weMemzxgtKei5Hb9rI6b2ZReNztXpeoYOMMKJOu9kmd385CMwhHZ2IkcX3aOLC/mlY1O5fO2RpsV2ca/Z/XWh5iA0usASOY9d/UqJTtmje6UKddTsnfivBGF9NyjUAL6WlJx60IkF/Fx7lyUOxFtVDlGdWXi0oTEkrh0lIyHlsIocNVrN7GT/BrXUk927oTxqfF1zCn2gDCtVD5P2w5LZBp4jhVQ3TXRsx9mImJjxUIti90CYTPQ4TqxQsFmLwvYaKfzV2bfHNUGJxi007oJFgotrPzM=
  - secure: SpM5YnklLlpvdOgDrcXKFCKRmS0o6+qveQep7aGXXdJoYkaxXKMGE7koj5yH9GgIqsHSMrkYlkRidEfGWVWnQ6VJGInlpmu8FcX67tsAE1NboQdrY1O9Zfk1g6xk8Y+91G1VmHewaKgJjrO89py8+XKEkOYmAM7/pChyZIS7Q6PBripntwaa0TU2qpNZSZomefmes0srksfPrEchTmn3IS1XiBB6geePreoZlAw8nI4XgdHcIWduGzXwwcrjghpvBxBGvc2aFnsOPoMAwn0ixqhHXEEZ0xBoj1xFjzWQwdKoVxWn+iRfLS3N+MKvljGN830RC79Z08xNq2eH+RK9nk3V14pveqNNgW5jGJQPMWEcvUgVluI0v6ZVTSQZHwKCZsPiQa4nYtX0gce6cx+CdsShSyn0jvgtwnUtbtqQQlI7JsdszexOncuozZj3xNsk51axSFnXopWgi2EFFZLw1vwgexSbLrUTXTOSlgggmlftbqcN47KszKTzkkkiBgQ9CFpp4MxYTnMReemaXDgVYLA5alD4DzVYBV2S9JISLsSiybcBdDYlypG3vYJ/xtjr0ETnMZuUF+5Qk+ypXsdOVQkIaVoUt9bs43mz7rtsLPqHIxFKpdeme3ZWUPbpVw0EbwOGfd24M2dfpWFWuprN22/6MxF5HkhdOnoMQyTOADg=
