dist: xenial
sudo: false
language: python
services:
  - memcached
python:
  - "3.6"

install:
  - sudo apt-get install -qq python-dev libxml2-dev libxmlsec1-dev
before_script:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install python-coveralls
  - pip install pycodestyle
  - pip install pytz
  - npm install jquery
  - npm install -g jshint
  - npm install -g mocha
  - npm install -g istanbul
  - npm install jsdom
  - npm install sinon
  - npm install coveralls
  - npm install -g --save-dev webpack
  - npm install -g webpack-cli
  - cp travis-ci/manage.py manage.py
  - python manage.py migrate

script:
  - pycodestyle endorsement/ --exclude=migrations,endorsement/static/vendor,endorsement/static/images,endorsement/static/fonts
  - jshint endorsement/static/endorsement/js/ --verbose
#  - mocha endorsement/static/js/test/ --recursive
  - webpack --mode=production
  - coverage run --source=endorsement/ --omit=endorsement/migrations/* manage.py test endorsement
after_script:
  - coveralls
notifications:
