version: '2'

services:
  app:
    environment:
      - ENV=localdev
      - PORT=8000
    restart: always
    container_name: app
    build:
      context: .
    volumes:
      - ./endorsement:/app/endorsement
    ports:
      - "8000:8000"
