# overrides below are 

overrides:
  bump-up:
    description: "Bump up min replicas to anticpate quick load spike"
    values:
      autoscaling:
        minReplicas: 2
        maxReplicas: 4
    timezone: 'US/Pacific'
    dates: 
      - '2021-03-04 12:55:00'
  restore-default:
    description: "Drop min replicas to default after anticipated load spike"
    values: []
    timezone: 'US/Pacific'
    dates:
      - '2021-03-03 12:00:00'
