autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
targetAverageUtilization: 100
resources:
  limits:
    cpu: 1.0
ingress:
  enabled: true
  type: nginx
  tls:
    prt-prod:
      secretName: provision.uw.edu-ingress-cert
      hosts:
        - provision.uw.edu
  hosts:
    prt-prod:
      host: provision.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
readiness:
  enabled: true
database:
  engine: postgres
  name: uw_service_endorsement
  hostname: provision-db-prod-service
  secretName: provision.uw.edu-sql-secret
externalService:
  enabled: true
  name: provision-db-prod-service
  type: ClusterIP
  serviceAddress: 172.18.1.16
  servicePort: 5432
repo: prt
instance: prod
image:
  repository: IMAGE_REGISTRY
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
memcached:
  enabled: true
  replicaCount: 1
cronjob:
  enabled: true
  jobs:
    - name: expire-endorsees
      schedule: "5 8 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["expire_endorsees"]
    - name: expiration-notice-1
      schedule: "10 8 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "1"]
    - name: expiration-notice-2
      schedule: "20 8 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "2"]
    - name: expiration-notice-3
      schedule: "30 8 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "3"]
    - name: expiration-notice-4
      schedule: "40 8 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "4"]
    - name: validate-endorsees
      schedule: "10 12 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["validate_endorsees"]
    - name: validate-endorsers
      schedule: "25 12 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["validate_endorsers"]
    - name: notify-endorsees
      schedule: "*/2 * * * *"
      command: ["/scripts/management_command.sh"]
      args: ["notify_endorsees"]
    - name: validate-shared-owners
      schedule: "15 11 * * *"
      command: ["/scripts/management_command.sh"]
      args: ["validate_shared_endorsers"]
certs:
  mounted: true
  certPath: /certs/provision.uw.edu-uwca.cert
  keyPath: /certs/provision.uw.edu-uwca.key
  secretName: provision.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: prod
  - name: ENDORSEMENT_SERVICES
    value: "canvas, google, office365, zoom_basic"
  - name: GWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: UWNETID_ENV
    value: PROD
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://provision.uw.edu/sso/
  - name: CLUSTER_CNAME
    value: provision.uw.edu
externalSecrets:
  enabled: true
  secrets:
    - name: provision.uw.edu-secrets
      externalKey: axdd/kv/data/provision/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
    - name: provision.uw.edu-sql-secret
      externalKey: axdd/kv/data/provision/prod/sql-secret
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: provision.uw.edu-uwca-certs
      externalKey: axdd/kv/data/provision/prod/uwca-certs
      data:
        - name: provision.uw.edu-uwca.key
          property: key
        - name: provision.uw.edu-uwca.cert
          property: cert
    - name: provision.uw.edu-ic-certs
      externalKey: axdd/kv/data/provision/prod/ic-certs
      data:
        - name: provision.uw.edu.cert
          property: cert
    - name: idp.uw-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: idp.uw-cert
          property: cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: provision.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: provision.uw.edu-secrets
    secretKey: email-host
  SAMLServiceProviderCert:
    name: SP_CERT
    secretName: provision.uw.edu-ic-certs
    secretKey: provision.uw.edu.cert
  SAMLIDPCert:
    name: IDP_CERT
    secretName: idp.uw-cert
    secretKey: idp.uw-cert
