ingress:
  enabled: true
  type: nginx
  tls:
    prt-prod:
      secretName: provision.uw.edu-ingress-1797eb351d9c0b9327e60afd48c1c16a
      hosts:
        - provision.uw.edu
  hosts:
    prt-prod:
      host: provision.uw.edu
      paths: 
        - "/"
database:
  engine: postgres
  name: uw_service_endorsement
  hostname: provision-db-prod-service
  secretName: provision-db-prod
externalService:
  enabled: true
  name: provision-db-prod-service
  type: ClusterIP
  serviceAddress: 172.18.1.16
  servicePort: 5432
repo: prt
instance: prod
replicaCount: 2
minReplicas: 2
maxReplicas: 6
targetAverageUtilization: 90
resources:
  limits:
    cpu: 600m
  requests:
    cpu: 200m
image:
  repository: registry.hub.docker.com/acait/prt
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: expire-endorsees
      schedule: "5 8 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expire_endorsees)"]'
    - name: expiration-notice-1
      schedule: "10 8 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expiration_notice 1)"]'
    - name: expiration-notice-2
      schedule: "20 8 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expiration_notice 2)"]'
    - name: expiration-notice-3
      schedule: "30 8 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expiration_notice 3)"]'
    - name: expiration-notice-4
      schedule: "40 8 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expiration_notice 4)"]'
    - name: validate-endorsees
      schedule: "10 12 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py validate_endorsees)"]'
    - name: validate-endorsers
      schedule: "25 12 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py validate_endorsers)"]'
    - name: notify-endorsees
      schedule: "*/2 * * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py notify_endorsees)"]'
    - name: validate-shared-owners
      schedule: "15 11 * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py validate_shared_endorsers)"]'
certs:
  mounted: true
  certPath: /certs/provision.uw.edu-uwca.cert
  keyPath: /certs/provision.uw.edu-uwca.key
  secretName: prt-prod-uwca-certs
environmentVariables:
  - name: ENV
    value: prod
  - name: CERT_PATH
    value: /certs/provision.uw.edu-uwca.cert
  - name: KEY_PATH
    value: /certs/provision.uw.edu-uwca.key
  - name: GWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: UWNETID_ENV
    value: PROD
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://provision.uw.edu/sso/
  - name: CLUSTER_CNAME
    value: provision.uw.edu
  - name: SP_CERT
    value: 'MIIEpDCCBA2gAwIBAgICMzgwDQYJKoZIhvcNAQELBQAwgZQxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMRQwEgYDVQQLEwtVVyBTZXJ2aWNlczEXMBUGA1UEAxMOVVcgU2VydmljZXMgQ0ExJjAkBgkqhkiG9w0BCQEWF2hlbHBAY2FjLndhc2hpbmd0b24uZWR1MB4XDTE4MDQxMDE3NDUwMVoXDTIxMDQxMTE3NDUwMVowgZ0xCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJXQTEQMA4GA1UEBwwHU2VhdHRsZTEhMB8GA1UECgwYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMRMwEQYDVQQLDApVVy1JVCBBWEREMRkwFwYDVQQDDBBwcm92aXNpb24udXcuZWR1MRwwGgYJKoZIhvcNAQkBFg1hY2EtaXRAdXcuZWR1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuQVBKpPdNtkrD5gT0D/f7gO0O4kfssejk/kkQZpDBw5U1aYLbATb406/XGilLgKCLqNxqPfTJWYOXlDKuaSSImbLSE5u8YJ6OBiD9PaODp51vDxLGGWcCtB8KZPS2+ENq8l8upAtwmQv/VjWlGK4B/HYWvkSN70YSibXbhsYHy9TJg89HWbkqz0SKS00MLRJJUCEwQkmvTPUodEY2hPYBfeAwxUOSGO0k4jGWXpTG4PuilrCzboRaySWENUdMTrD4thr7HYFZid9oAGJjwctVUBJgqh2De92D+MS18vSlxjOW9mVpHx1P9vHqUr78hik7dLzXDwUeLI9EaZ4GOZWIwIDAQABo4IBdDCCAXAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwHQYDVR0OBBYEFEpz3n6+AJ3IBh5Dlc754QB9g9EQMBsGA1UdEQQUMBKCEHByb3Zpc2lvbi51dy5lZHUwgcEGA1UdIwSBuTCBtoAUVdfBM8b6k/gnPcsgS/VajliXfXShgZqkgZcwgZQxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMRQwEgYDVQQLEwtVVyBTZXJ2aWNlczEXMBUGA1UEAxMOVVcgU2VydmljZXMgQ0ExJjAkBgkqhkiG9w0BCQEWF2hlbHBAY2FjLndhc2hpbmd0b24uZWR1ggEAMEEGA1UdHwQ6MDgwNqA0oDKGMGh0dHA6Ly9jZXJ0cy5jYWMud2FzaGluZ3Rvbi5lZHUvVVdTZXJ2aWNlc0NBLmNybDANBgkqhkiG9w0BAQsFAAOBgQCf/i1Fkq/4kJWD81xQAG0qNEiJ3f0ex5kSHqXQPIPW3Cx9gjxRKElvdSe89GOvEx2xuYxdDt8AUvdyuBNgpJ775li21kqdvT6ulOcBCNX2J7dmwa7gwzhHdE+pdgB1i9v3NM3/v8BhBr6JMCM5awn3SbJGNJ19WVhIe0TW/5oSAA=='
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: prt-prod-django-secret
    secretKey: django-secret
  emailHostUser:
    name: EMAIL_HOST_USER
    secretName: email-post-credentials
    secretKey: username
  emailHostPassword:
    name: EMAIL_HOST_PASSWORD
    secretName: email-post-credentials
    secretKey: password
