autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
ingress:
  enabled: true
  type: nginx
  tls:
    test-prt:
      secretName: test.provision.uw.edu-ingress-cert
      hosts:
        - test.provision.uw.edu
  hosts:
    test-prt:
      host: test.provision.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
securityPolicy:
  enabled: true
readiness:
  enabled: true
database:
  engine: postgres
  name: uw_service_endorsement_test
  hostname: provision-db-test-service
  secretName: test.provision.uw.edu-sql-secret
externalService:
  enabled: true
  name: provision-db-test-service
  type: ClusterIP
  serviceAddress: 172.18.1.16
  servicePort: 5432
repo: prt
instance: test
targetAverageUtilization: 95
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 15m
    memory: 150Mi
image:
  repository: IMAGE_REGISTRY
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
memcached:
  enabled: true
  replicaCount: 1
cronjob:
  enabled: true
  jobs:
    - name: expire-endorsees
      schedule: "5 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["expire_endorsees"]
    - name: expiration-notice-1
      schedule: "10 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "1"]
    - name: expiration-notice-2
      schedule: "15 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "2"]
    - name: expiration-notice-3
      schedule: "20 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "3"]
    - name: expiration-notice-4
      schedule: "25 8 * * 1-5"
      command:
        - /scripts/management_command.sh
      args:
        - expiration_notice
        - "4"
    - name: reconcile-access
      schedule: "1 6 * * 3,6"
      command: ["/scripts/management_command.sh"]
      args: ["reconcile_access"]
daemon:
  enabled: true
  daemons:
    - name: notify-endorsees
      command: ["/scripts/management_daemon.sh"]
      args: ['--cron', '*/5 * * * *', 'notify_provisionees']
certs:
  mounted: true
  certPath: /certs/test.provision.uw.edu.cert
  keyPath: /certs/test.provision.uw.edu.key
  secretName: test.provision.uw.edu-ic-certs
environmentVariables:
  - name: ENV
    value: dev
  - name: PWS_ENV
    value: PROD
  - name: GWS_ENV
    value: PROD
  - name: UWNETID_ENV
    value: EVAL
  - name: MSCA_ENV
    value: PROD
  - name: MSCA_TIMEOUT
    value: "60"
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test.provision.uw.edu/saml
  - name: CLUSTER_CNAME
    value: test.provision.uw.edu
  - name: ENDORSEMENT_PROVISIONING
    value: services,mailbox_access,shared_drives
externalSecrets:
  enabled: true
  secrets:
    - name: test.provision.uw.edu-secrets
      externalKey: provision/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: itbill-host
          property: itbill-host
        - name: itbill-basic-auth
          property: itbill-basic-auth
        - name: itbill-shared-drive-product-sys-id
          property: itbill-shared-drive-product-sys-id
        - name: itbill-form-url-base-id
          property: itbill-form-url-base-id
        - name: itbill-form-url-sys-id
          property: itbill-form-url-sys-id
        - name: msca-oauth-token-url
          property: msca-oauth-token-url
        - name: msca-report-scope
          property: msca-report-scope
        - name: msca-client-id
          property: msca-client-id
        - name: msca-client-secret
          property: msca-client-secret
        - name: email-host
          property: email-host
        - name: msca-subscription-key
          property: msca-subscription-key
        - name: safe-email-recipient
          property: safe-email-recipient
        - name: safe-email-safelist
          property: safe-email-safelist
    - name: test.provision.uw.edu-sql-secret
      externalKey: provision/test/sql-secret
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: test.provision.uw.edu-ic-certs
      externalKey: provision/test/ic-certs
      data:
        - name: test.provision.uw.edu.cert
          property: cert
        - name: test.provision.uw.edu.key
          property: key
    - name: idp.uw-cert
      externalKey: idp-cert
      data:
        - name: idp.uw-cert
          property: cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.provision.uw.edu-secrets
    secretKey: django-secret
  ITBillHost:
    name: ITBILL_HOST:
    secretName: test.provision.uw.edu-secrets
    secretKey: itbill-host
  ITBillBasicAuth:
    name: ITBILL_BASIC_AUTH
    secretName: test.provision.uw.edu-secrets
    secretKey: itbill-basic-auth
  ITBillSharedDriveProductSYSID:
    name: ITBILL_SHARED_DRIVE_PRODUCT_SYS_ID
    secretName: test.provision.uw.edu-secrets
    secretKey: itbill-shared-drive-product-sys-id
  ITBillFormURLBaseID:
    name: ITBILL_FORM_URL_BASE_ID
    secretName: test.provision.uw.edu-secrets
    secretKey: itbill-form-url-base-id
  ITBillFormURLSYSID:
    name: ITBILL_FORM_URL_SYS_ID
    secretName: test.provision.uw.edu-secrets
    secretKey: itbill-form-url-sys-id
  MSCA_OAUTH_TOKEN_URL:
    name: MSCA_OAUTH_TOKEN_URL
    secretName: test.provision.uw.edu-secrets
    secretKey: msca-oauth-token-url
  MSCAReportScope:
    name: MSCA_REPORT_SCOPE
    secretName: test.provision.uw.edu-secrets
    secretKey: msca-report-scope
  MSCAClientID:
    name: MSCA_CLIENT_ID
    secretName: test.provision.uw.edu-secrets
    secretKey: msca-client-id
  MSCAClientSecret:
    name: MSCA_CLIENT_SECRET
    secretName: test.provision.uw.edu-secrets
    secretKey: msca-client-secret
  emailHost:
    name: EMAIL_HOST
    secretName: test.provision.uw.edu-secrets
    secretKey: email-host
  MSCASubscriptionKey:
    name: MSCA_SUBSCRIPTION_KEY
    secretName: test.provision.uw.edu-secrets
    secretKey: msca-subscription-key
  SafeEmailRecipient:
    name: SAFE_EMAIL_RECIPIENT
    secretName: test.provision.uw.edu-secrets
    secretKey: safe-email-recipient
  SafeEmailSafelist:
    name: SAFE_EMAIL_SAFELIST
    secretName: test.provision.uw.edu-secrets
    secretKey: safe-email-safelist
  SAMLServiceProviderCert:
    name: SP_CERT
    secretName: test.provision.uw.edu-ic-certs
    secretKey: test.provision.uw.edu.cert
  SAMLIDPCert:
    name: IDP_CERT
    secretName: idp.uw-cert
    secretKey: idp.uw-cert
