autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
ingress:
  enabled: true
  type: nginx
  tls:
    test-prt:
      secretName: test.provision.uw.edu-ingress-cert
      hosts:
        - test.provision.uw.edu
  hosts:
    test-prt:
      host: test.provision.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
securityPolicy:
  enabled: true
readiness:
  enabled: true
database:
  engine: postgres
  name: uw_service_endorsement_test
  hostname: provision-db-test-service
  secretName: test.provision.uw.edu-sql-secret
externalService:
  enabled: true
  name: provision-db-test-service
  type: ClusterIP
  serviceAddress: 172.18.1.16
  servicePort: 5432
repo: prt
instance: test
targetAverageUtilization: 95
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 25m
    memory: 128Mi
image:
  repository: registry.hub.docker.com/acait/prt
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
memcached:
  enabled: true
  replicaCount: 1
cronjob:
  enabled: true
  jobs:
    - name: expire-endorsees
      schedule: "5 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["expire_endorsees"]
    - name: expiration-notice-1
      schedule: "10 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "1"]
    - name: expiration-notice-2
      schedule: "15 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "2"]
    - name: expiration-notice-3
      schedule: "20 8 * * 1-5"
      command: ["/scripts/management_command.sh"]
      args: ["expiration_notice", "3"]
    - name: expiration-notice-4
      schedule: "25 8 * * 1-5"
      command:
        - /scripts/management_command.sh
      args:
        - expiration_notice
        - "4"
daemon:
  enabled: true
  daemons:
    - name: notify-endorsees
      command: ["/scripts/management_daemon.sh"]
      args: ['--cron', '*/5 * * * *', 'notify_endorsees']
certs:
  mounted: true
  certPath: /certs/provision-test.uw.edu-uwca.cert
  keyPath: /certs/provision-test.uw.edu-uwca.key
  secretName: test.provision.uw.edu-uwca-certs
environmentVariables:
  - name: ENV
    value: dev
  - name: WEBSERVER
    value: nginx
  - name: GWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: UWNETID_ENV
    value: EVAL
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://test.provision.uw.edu/saml
  - name: CLUSTER_CNAME
    value: test.provision.uw.edu
  - name: SAFE_EMAIL_RECIPIENT
    value: "mikes@uw.edu"
externalSecrets:
  enabled: true
  secrets:
    - name: test.provision.uw.edu-secrets
      externalKey: axdd/kv/data/provision/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host
          property: email-host
    - name: test.provision.uw.edu-sql-secret
      externalKey: axdd/kv/data/provision/test/sql-secret
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: test.provision.uw.edu-uwca-certs
      externalKey: axdd/kv/data/provision/test/uwca-certs
      data:
        - name: provision-test.uw.edu-uwca.key
          property: key
        - name: provision-test.uw.edu-uwca.cert
          property: cert
    - name: test.provision.uw.edu-ic-certs
      externalKey: axdd/kv/data/provision/test/ic-certs
      data:
        - name: provision-test.uw.edu.cert
          property: cert
    - name: idp.uw-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: idp.uw-cert
          property: cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.provision.uw.edu-secrets
    secretKey: django-secret
  emailHost:
    name: EMAIL_HOST
    secretName: test.provision.uw.edu-secrets
    secretKey: email-host
  SAMLServiceProviderCert:
    name: SP_CERT
    secretName: test.provision.uw.edu-ic-certs
    secretKey: provision-test.uw.edu.cert
  SAMLIDPCert:
    name: IDP_CERT
    secretName: idp.uw-cert
    secretKey: idp.uw-cert
