ingress:
  enabled: true
  type: nginx
  tls:
    test-prt:
      secretName: test.provision.uw.edu-81d5204cb79db9dc4f5489b6da81fa4a
      hosts:
        - test.provision.uw.edu
    prt-test:
      secretName: provision-test.uw.edu
      hosts:
        - provision-test.uw.edu
  hosts:
    test-prt:
      host: test.provision.uw.edu
      paths:
        - "/"
    prt-test:
      host: provision-test.uw.edu
      paths:
        - "/"
    prt-test-aca-aws:
      host: prt-test.aca-aws.s.uw.edu
      paths:
        - "/"
database:
  engine: postgres
  name: uw_service_endorsement
  hostname: provision-db-test-service
  secretName: provision-db-test
externalService:
  enabled: true
  name: provision-db-test-service
  type: ClusterIP
  serviceAddress: 172.18.1.14
  servicePort: 5432
repo: prt
instance: test
replicaCount: 2
minReplicas: 2
maxReplicas: 6
targetAverageUtilization: 90
resources:
  limits:
    cpu: 600m
  requests:
    cpu: 200m
image:
  repository: registry.hub.docker.com/acait/prt
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: expire-endorsees
      schedule: "5 8 * * 1-5"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expire_endorsees)"]'
    - name: expiration-notice-1
      schedule: "10 8 * * 1-5"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expiration_notice 1)"]'
    - name: expiration-notice-2
      schedule: "15 8 * * 1-5"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expiration_notice 2)"]'
    - name: expiration-notice-3
      schedule: "20 8 * * 1-5"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expiration_notice 3)"]'
    - name: expiration-notice-4
      schedule: "25 8 * * 1-5"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expiration_notice 4)"]'
#    - name: validate-endorsees
#      schedule: "10 12 * * 1-5"
#      command: '["bash"]'
#      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py validate_endorsees)"]'
#    - name: validate-endorsers
#      schedule: "25 12 * * 1-5"
#      command: '["bash"]'
#      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py validate_endorsers)"]'
#    - name: notify-endorsers
#      schedule: "*/5 * * * *"
#      command: '["bash"]'
#      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py notify_endorsers)"]'
    - name: notify-endorsees
      schedule: "*/5 * * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py notify_endorsees)"]'
#    - name: validate-shared-owners
#      schedule: "15 11 * * *"
#      command: '["bash"]'
#      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py validate_shared_endorsers)"]'
certs:
  mounted: true
  certPath: /certs/provision-test.uw.edu-uwca.cert
  keyPath: /certs/provision-test.uw.edu-uwca.key
  secretName: prt-test-uwca-certs
environmentVariables:
  - name: ENV
    value: dev
  - name: GWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: UWNETID_ENV
    value: EVAL
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://provision-test.uw.edu/sso/
  - name: CLUSTER_CNAME
    value: provision-test.uw.edu
  - name: SP_CERT
    value: 'MIIG/jCCBeagAwIBAgIQOeqKxgWMAi4IK+4DpH26uDANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTAeFw0yMDAzMTkwMDAwMDBaFw0yMjAzMTkyMzU5NTlaMIGyMQswCQYDVQQGEwJVUzEOMAwGA1UEERMFOTgxOTUxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1NlYXR0bGUxGTAXBgNVBAkTEDQ1NDUgMTV0aCBBdmUgTkUxITAfBgNVBAoTGFVuaXZlcnNpdHkgb2YgV2FzaGluZ3RvbjEOMAwGA1UECxMFVVctSVQxHjAcBgNVBAMTFXByb3Zpc2lvbi10ZXN0LnV3LmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJx6NZbz60e/ysmD1ymmGs0fktxx/t3Jjf+1ieGgVVcYQoqQu1q2qYgpB1VngA0uz2MWqFBER5EY6mAWDnqhV5ssIezZrVcsQrK4Jbe/Nu9KZ/KhI8uOSf43z/qAU0DcjkHnTL9IBM2uPPK1SCpOw/hkvtUD50HyuKWymdJKixBUEPaJoVehQGZX2xPmUlvoY87btdWiwxgKj1iB0RczWq78ocFPpIc40AIoRMKo6jCt1dUDxCCOcEgONBFXtCYKyl35LPPaqTkjM3bOJsIg1+c2h1NE8lbjhiAin4aF6Wa0yuNhNIHUHiwGKKc+9WvQmdi5fPtiR9q5yj8kDGd7s3MCAwEAAaOCA0kwggNFMB8GA1UdIwQYMBaAFB4Fo3ePbJbiW4dLprSGrHEADOc4MB0GA1UdDgQWBBQPAcGxTnoV+G9f4M3Y3vieQ+Nf3DAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwZwYDVR0gBGAwXjBSBgwrBgEEAa4jAQQDAQEwQjBABggrBgEFBQcCARY0aHR0cHM6Ly93d3cuaW5jb21tb24ub3JnL2NlcnQvcmVwb3NpdG9yeS9jcHNfc3NsLnBkZjAIBgZngQwBAgIwRAYDVR0fBD0wOzA5oDegNYYzaHR0cDovL2NybC5pbmNvbW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBU2VydmVyQ0EuY3JsMHUGCCsGAQUFBwEBBGkwZzA+BggrBgEFBQcwAoYyaHR0cDovL2NydC51c2VydHJ1c3QuY29tL0luQ29tbW9uUlNBU2VydmVyQ0FfMi5jcnQwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20wIAYDVR0RBBkwF4IVcHJvdmlzaW9uLXRlc3QudXcuZWR1MIIBfAYKKwYBBAHWeQIEAgSCAWwEggFoAWYAdQBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiFq/L8cP5tRwAAAXDzuDgrAAAEAwBGMEQCIAW58QyqdIbbRJm/vmQhHj7JmYCrzQ5E77azV477F8BFAiA9iXXdVrXJuU2Fi0tmgDvL4eUnC9Hd29Q37zZAwzq6DwB1AN+lXqtogk8fbK3uuF9OPlrqzaISpGpejjsSwCBEXCpzAAABcPO4N/EAAAQDAEYwRAIgXcIPgn9yiKftTcsD1886LMN45Tua/tqfM4kgCC2rsvcCIC1q2a4zdwxXLJvXqsWikyQFkZFVi4MYmGAqfni6ZvvKAHYAQcjKsd8iRkoQxqE6CUKHXk4xixsD6+tLx2jwkGKWBvYAAAFw87g4GgAABAMARzBFAiAPWF9l2RmBe0I0y6jm95SUxdh1ZoHUIgskXXYT8PbzOAIhAMRgiBiYTG4ctCN3FhSVx/Z9MHi3rIYTiqMzQahSn4moMA0GCSqGSIb3DQEBCwUAA4IBAQAF9otGvD/+/MxAxrnTv0Sb519cxC9vMkP0+399w/x+1q8w5kiExIe7llH/rPRv+crEV08J/wBmVXDOIbgmn1eYqzBYrPballs8+wGl+I2yLBF+WraX4ROJNkclvJhrTnnfVm589lOvJXhWMvtfxH02kfjr9vrd3xsHUm9bj5DbEUNelYCjPe2n/Zcq94dTFLLiI7ATIQWmF5+Fkd4XwjszRrr2m0le1WMPgDDiD4RIjqHv/y7jP3gMSxz6P5Upn+2CmzZYoFRiUQTJErJWb/q1S9wX0qjMNEqzIUNwPhlipTOF5EaYTVj1yR28dbPTxDJhQ/rJXrcr4h4X+IW6W0wB'
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
  - name: SAFE_EMAIL_RECIPIENT
    value: "mikes@uw.edu"
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: prt-test-django-secret
    secretKey: django-secret
  emailHostUser:
    name: EMAIL_HOST_USER
    secretName: email-post-credentials
    secretKey: username
  emailHostPassword:
    name: EMAIL_HOST_PASSWORD
    secretName: email-post-credentials
    secretKey: password
