ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    prt-test:
      secretName: provision-test.uw.edu
      hosts:
        - provision-test.uw.edu
  hosts:
    prt-test:
      host: provision-test.uw.edu
      paths: 
        - "/"
    prt-test-aca-aws:
      host: prt-test.aca-aws.s.uw.edu
      paths: 
        - "/"
database:
  engine: postgres
  name: uw_service_endorsement
  hostname: provision-db-test-service
  secretName: provision-db-test
externalService:
  enabled: true
  name: provision-db-test-service
  type: ClusterIP
  serviceAddress: 172.18.1.14
  servicePort: 5432
repo: prt
instance: test
image:
  repository: registry.hub.docker.com/acait/prt-test
commitHash: '20191008.1'
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
cronjob:
  enabled: true
  jobs:
    - name: expire-endorsees
      schedule: "5 0 * * 1-5"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py expire_endorsees)"]'
    - name: validate-endorsees
      schedule: "10 4 * * 1-5"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py validate_endorsees)"]'
    - name: validate-endorsers
      schedule: "25 4 * * 1-5"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py validate_endorsers)"]'
    - name: notify-endorsers
      schedule: "*/5 * * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py notify_endorsers)"]'
    - name: notify-endorsees
      schedule: "*/5 * * * *"
      command: '["bash"]'
      args: '["-c", "(cd /app && source ./bin/activate && ./bin/python manage.py notify_endorsees)"]'
certs:
  mounted: true
  certPath: /certs/provision-test.uw.edu-uwca.cert
  keyPath: /certs/provision-test.uw.edu-uwca.key
  secretName: prt-test-uwca-certs
environmentVariables:
  - name: CERT_PATH
    value: /certs/provision-test.uw.edu-uwca.cert
  - name: KEY_PATH
    value: /certs/provision-test.uw.edu-uwca.key
  - name: GWS_ENV
    value: PROD
  - name: PWS_ENV
    value: PROD
  - name: UWNETID_ENV
    value: EVAL
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://provision-test.uw.edu/sso/
  - name: CLUSTER_CNAME
    value: provision-test.uw.edu
  - name: SP_CERT
    value: 'MIIG+DCCBeCgAwIBAgIQf72V62WTWh+YkcvcSmy8gTANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTAeFw0xODAzMjcwMDAwMDBaFw0yMDAzMjYyMzU5NTlaMIGqMQswCQYDVQQGEwJVUzEOMAwGA1UEERMFOTgxOTUxCzAJBgNVBAgTAldBMRAwDgYDVQQHEwdTZWF0dGxlMRkwFwYDVQQJExA0NTQ1IDE1dGggQXZlIE5FMSEwHwYDVQQKExhVbml2ZXJzaXR5IG9mIFdhc2hpbmd0b24xDjAMBgNVBAsTBVVXLUlUMR4wHAYDVQQDExVwcm92aXNpb24tdGVzdC51dy5lZHUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcejWW8+tHv8rJg9cpphrNH5Lccf7dyY3/tYnhoFVXGEKKkLtatqmIKQdVZ4ANLs9jFqhQREeRGOpgFg56oVebLCHs2a1XLEKyuCW3vzbvSmfyoSPLjkn+N8/6gFNA3I5B50y/SATNrjzytUgqTsP4ZL7VA+dB8rilspnSSosQVBD2iaFXoUBmV9sT5lJb6GPO27XVosMYCo9YgdEXM1qu/KHBT6SHONACKETCqOowrdXVA8QgjnBIDjQRV7QmCspd+Szz2qk5IzN2zibCINfnNodTRPJW44YgIp+GhelmtMrjYTSB1B4sBiinPvVr0JnYuXz7Ykfauco/JAxne7NzAgMBAAGjggNLMIIDRzAfBgNVHSMEGDAWgBQeBaN3j2yW4luHS6a0hqxxAAznODAdBgNVHQ4EFgQUDwHBsU56FfhvX+DN2N74nkPjX9wwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMGcGA1UdIARgMF4wUgYMKwYBBAGuIwEEAwEBMEIwQAYIKwYBBQUHAgEWNGh0dHBzOi8vd3d3LmluY29tbW9uLm9yZy9jZXJ0L3JlcG9zaXRvcnkvY3BzX3NzbC5wZGYwCAYGZ4EMAQICMEQGA1UdHwQ9MDswOaA3oDWGM2h0dHA6Ly9jcmwuaW5jb21tb24tcnNhLm9yZy9JbkNvbW1vblJTQVNlcnZlckNBLmNybDB1BggrBgEFBQcBAQRpMGcwPgYIKwYBBQUHMAKGMmh0dHA6Ly9jcnQudXNlcnRydXN0LmNvbS9JbkNvbW1vblJTQVNlcnZlckNBXzIuY3J0MCUGCCsGAQUFBzABhhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMCAGA1UdEQQZMBeCFXByb3Zpc2lvbi10ZXN0LnV3LmVkdTCCAX4GCisGAQQB1nkCBAIEggFuBIIBagFoAHYA7ku9t3XOYLrhQmkfq+GeZqMPfl+wctiDAMR7iXqo/csAAAFiaKRyKgAABAMARzBFAiADlvOHZtE16fIfilK++0pXUzP9WCGjXx7Dzo2u7yYmygIhALWSGxMjA2IPT12PmVAxE/mFjop2vpai4GK9yPYgCV3eAHUAXqdz+d9WwOe1Nkh90EngMnqRmgyEoRIShBh1loFxRVgAAAFiaKRydwAABAMARjBEAiB0qXI/J5ogy9SveOWrXttUocyUujPFAdCjah9xU1t1QgIgUrEcZfTqX6yKjtDQhyiZMpGSwu+TPLQBpz2KH6vQQHkAdwBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAWJopHIhAAAEAwBIMEYCIQCb5Ow5QUJaf7pMIcuh67TaGF3zqDNQEqPoAj9Nuo/TVAIhAJPNW79sWmwL10WSHrCIuQHKte5c2NNSCpsMHqWy9MU5MA0GCSqGSIb3DQEBCwUAA4IBAQBPkXQdZo+U8zhvXpIeXdVFkjbMPY3AaeAUWI0TxvwjwhFdYpoxExiJaAy3ZmhhaQpPHrlsxVeS1oUuPuEgD6UD89m8mHRNaln+6GcnxvICJilZrBJ013qAbfULHoGKp6pqZtQWyv2MtqDQvd7lhGYvPmIo26+fwFWMBbBVJrcPypgiwVyNNEHrt5WzKIUYRKDLFmnoqyBTARusxJ+JxQ3uLEEN+G/EmZhCEoR9MFKGtrRo9+MnQkwY4Fop3Cdoa3Zf9Z+Ik9ung44kqEsoR7Oeu6pUR8Jesq/uewMzuTkAPF3dS2XusTqURQoX3FqtixZGBTDgbhokcc9pWA2r3V50'
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='
  - name: SAFE_EMAIL_RECIPIENT
    value: "mikes@uw.edu"
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: prt-test-django-secret
    secretKey: django-secret
  emailHostUser:
    name: EMAIL_HOST_USER
    secretName: email-post-credentials
    secretKey: username
  emailHostPassword:
    name: EMAIL_HOST_PASSWORD
    secretName: email-post-credentials
    secretKey: password
