from django.test import TestCase
from endorsement.test.dao.endorse import TestEndorseDao
from endorsement.test.dao.gws import TestGwsDao
from endorsement.test.dao.migration import TestMigration
from endorsement.test.dao.pws import TestPwsDao
from endorsement.test.dao.user import TestUserDao
from endorsement.test.dao.uwnetid_subscription_60 import TestNetidSubs60Dao
#from endorsement.test.views.page import TestPage
from endorsement.test.views.session import TestLogSession
