---
name: Build, Test and Deploy

env:
  RELEASE_NAME: prt
  DJANGO_APP: endorsement

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, reopened, synchronize]

jobs:
  context:
    runs-on: ubuntu-20.04

    outputs:
      commit_hash: ${{ steps.context.outputs.commit_hash }}
      git_repo_branch: ${{ steps.context.outputs.git_repo_branch }}
      image_tag: ${{ steps.context.outputs.image_tag }}

    steps:
      - name: Set up Context
        id: context
        uses: uw-it-aca/actions/cicd-context@feature/set-output-deprecated
        with:
          release_name: ${{ env.RELEASE_NAME }}

  build:
    runs-on: ubuntu-20.04

    needs: context

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6

      - name: Run Python Linters
        uses: uw-it-aca/actions/python-linters@main
        with:
          app_name: ${DJANGO_APP}
          exclude_paths: 'migrations'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-$(echo ${{ hashFiles('Dockerfile') }} | head -c 16)
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build App Image
        uses: docker/build-push-action@v3
        with:
          target: app-container
          tags: ${{ needs.context.outputs.image_tag }}
          push: false
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build Test Image
        uses: docker/build-push-action@v3
        with:
          target: app-test-container
          tags: app-test-container
          push: false
          load: true

      - name: Run Tests in Image
        id: tests
        shell: bash
        run: >-
          docker run -u root -t
          -v ${PWD}:/coverage
          -e DJANGO_APP="$DJANGO_APP"
          -e "ENV=localdev" -e "AUTH=SAML_MOCK"
          app-test-container
          bash -c ". ./docker/test.sh"

      - name: Record Test Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          python -m pip install --upgrade pip coverage coveralls==2.2.0
          coverage combine
          coveralls

      - name: Push Image to GCR
        if: github.event_name == 'push'
        uses: uw-it-aca/actions/gcr-push@feature/set-output-deprecated
        with:
          image_tag: ${{ needs.context.outputs.image_tag }}
          gcp_json_key: ${{ secrets.GCP_JSON_KEY }}

  deploy:
    if: github.event_name == 'push'

    needs: [context, build]

    runs-on: ubuntu-20.04

    outputs:
      context: ${{ steps.context.outputs.context }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deployment Pipeline
        if: >-
          contains(fromJSON('["main", "develop"]'),
            needs.context.outputs.git_repo_branch)
        uses: uw-it-aca/actions/cicd-deploy@feature/set-output-deprecated
        with:
          release_name: ${{ env.RELEASE_NAME }}
          gh_auth_token: ${{ secrets.GH_AUTH_TOKEN }}
          commit_hash: ${{ needs.context.outputs.commit_hash }}
          git_repo_branch: ${{ needs.context.outputs.git_repo_branch }}
          registry_hostname: us-docker.pkg.dev
          registry_path: containers

      - name: 'Surface context from executed build step'
        id: context
        shell: bash
        run: echo "context=$(< ${CONTEXT_FILENAME})" >> $GITHUB_OUTPUT

  housekeeping:
    if: github.event_name == 'push'

    needs: [context, build, deploy]

    runs-on: ubuntu-20.04

    steps:
      - name: House Keeping
        uses: uw-it-aca/actions/cicd-housekeeping@feature/set-output-deprecated
        with:
          release_name: ${{ env.RELEASE_NAME }}
          gh_auth_token: ${{ secrets.GH_AUTH_TOKEN }}
          registry_password: ${{ secrets.GCP_JSON_KEY }}
          context: ${{ needs.deploy.outputs.context }}
