---
name: build-test-deploy-containerized-python-app

env:
  RELEASE_NAME: prt
  DJANGO_APP: endorsement
  COMMIT_HASH: $(git rev-parse --short=7 ${{ github.sha }})

on:
  push:
    branches:
      - feature/github-actions

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        id: repo
        env:
          IMAGE_TAG: "${{ env.RELEASE_NAME }}:${{ env.COMMIT_HASH }}"

      - name: Build App Images for ${{ repo.env.IMAGE_TAG }}
        id: docker_build
        run: |
          docker build --target app-container -t "${{ repo.env.IMAGE_TAG }}" .
          docker build -t app-test-container .

      - name: Prep Test Tooling
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          run: |
            python -m pip install --upgrade pip
            pip install coverage
            pip install coveralls

      - name: Run Tests
        shell: bash
        run: |
          docker run -u root -it -v /tmp:/coverage
            -e DJANGO_APP="${{ env.DJANGO_APP }}"
            -e "ENV=localdev" -e "AUTH=SAML_MOCK"
            app-test-container
            bash -c ". ./docker/test.sh"

      - name: Record Test Results
        shell: bash
        run: |
          cp /tmp/.coverage.* .
          coverage combine
          coveralls
