---
name: cicd

env:
  RELEASE_NAME: prt
  DJANGO_APP: endorsement
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - feature/github-actions
  pull_request:
    branches:
      - feature/github-actions

jobs:
  pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set Commit Hash
        run: echo "COMMIT_HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Set Image Tag
        run: >-
          echo "IMAGE_TAG=${{ env.RELEASE_NAME }}:${{ env.COMMIT_HASH }}"
          >> $GITHUB_ENV

      - name: Build App and Test Images
        id: docker_build
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
          docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
          docker build --target app-container -t "${{ env.IMAGE_TAG }}" --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache .
          docker tag "${{ env.IMAGE_TAG }}" docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
          docker build --target app-test-container -t app-test-container --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache .

      - name: Install Test Tooling
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install coveralls

      - name: Test Images
        shell: bash
        run: >-
          docker run -u root -t
          -v /tmp:/coverage
          -e DJANGO_APP="${{ env.DJANGO_APP }}"
          -e "ENV=localdev" -e "AUTH=SAML_MOCK"
          app-test-container
          bash -c ". ./docker/test.sh"

      - name: Record Test Results
        shell: bash
        run: |
          cp /tmp/.coverage.* .
          coverage combine
          coveralls

      - name: Deploy Image
        if: github.event.pull_request.merged == ''
        env:
          GH_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GCP_JSON_KEY: gcp.json
          TRAVIS_BRANCH: ${{ github.base_ref }}
          TRAVIS_REPO_SLUG: ${{ github.repository }}
          TRAVIS_BUILD_NUMBER: ${{ github.run_id }}
          TRAVIS_BUILD_WEB_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          echo "${{ secrets.TEST_SECRET }}" | base64 -d > ${GCP_JSON_KEY}
          curl -Ls https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/feature/dump-env/travis-ci/dumpenv.sh | bash
