---
name: UW Registration Period Load Preparation

env:
  RELEASE_NAME: prt
  DJANGO_APP: endorsement
  OVERRIDE_REF: refs/heads/feature/github-actions
  OVERRIDE_CONFIG: docker/overrides.yml
  OVERRIDE_FILE: ./overrides.yml

on:
  push:
    branches: [feature/github-actions]
#  schedule:
#    - cron: "*/15 * * * *"

jobs:
  override:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.OVERRIDE_REF }}

      - name: Generate Override Values
        id: override
        uses: uw-it-aca/actions/time-values@feature/time-values
        with:
          config_file: ${{ env.OVERRIDE_CONFIG }}

      - name: Write Overrides to File
        if: ${{ steps.override.outputs.values != '' }}
        run: |
          echo "${{ steps.override.outputs.values }}" > $OVERRIDE_FILE

      - name: Set up Context
        if: ${{ steps.override.outputs.values != '' }}
        id: cicd
        uses: uw-it-aca/actions/cicd-context@v1.4
        with:
          release_name: ${{ env.RELEASE_NAME }}

      - name: Deploy with Overridden Values
        if: ${{ steps.override.outputs.values != '' }}
        shell: bash
        run: |
          echo "Would override values file ${OVERRIDE_FILE}:"
          cat $OVERRIDE_FILE
##        uses: uw-it-aca/actions/cicd-deploy@main
##        with:
##          release_name: ${{ env.RELEASE_NAME }}
##          commit_hash: ${{ steps.cicd.outputs.commit_hash }}
##          git_repo_branch: ${{ steps.cicd.outputs.git_repo_branch }}
##          gh_auth_token: ${{ secrets.GH_AUTH_TOKEN }}
##          helm_override_values_file: ${{ env.OVERRIDE_FILE }}

